name: Build and Deploy JupyterBook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my-jupyterbook-env
          environment-file: environment.yml
          python-version: "3.9"
          auto-update-conda: true
          auto-activate-base: false

      - name: Verify Installation
        shell: bash -l {0}  # Use login shell for activation
        run: |
          conda activate my-jupyterbook-env
          conda list
          which jupyter-book

      - name: Build JupyterBook
        shell: bash -l {0} # Use login shell for activation
        run: |
          conda activate my-jupyterbook-env
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2