name: Build and Deploy JupyterBook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3 # Use v3
        with:
          activate-environment: my-jupyterbook-env
          environment-file: environment.yml # Use the environment.yml file
          python-version: "3.9"
          auto-update-conda: true
          auto-activate-base: false

      - name: Build JupyterBook
        run: jupyter-book build .  #  Add the dot to specify the current directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2