name: Build and Deploy JupyterBook

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your Python version

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: my-jupyterbook-env  # Replace with your environment name
          environment-file: requirements.txt
          python-version: "3.9"  # Or your Python version
          auto-update-conda: true
          auto-activate-base: false

      - name: Build JupyterBook
        run: jupyter-book build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2