name: Build and Deploy JupyterBook

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          conda install -c conda-forge jupyter-book

      - name: Build JupyterBook
<<<<<<< Updated upstream:.github/workflows/build-and-deploy.yml
        run: jupyter-book build LetsMachineLearn
=======
        run: jupyter-book build  # Corrected
>>>>>>> Stashed changes:.github/workflows/build-and-deploy.yml

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
<<<<<<< Updated upstream:.github/build-and-deploy.yml
          path:./mybook/_build/html  # Path to your built book
=======
          path:./_build/html   # Corrected
>>>>>>> Stashed changes:.github/workflows/build-and-deploy.yml
