name: Build and Deploy JupyterBook
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my-jupyterbook-env
          environment-file: environment.yml
          python-version: "3.9"
          auto-update-conda: true
          auto-activate-base: false
      - name: Verify Installation
        shell: bash -l {0}
        run: |
          conda activate my-jupyterbook-env
          conda list
          which jupyter-book
      - name: Build JupyterBook
        shell: bash -l {0}
        run: |
          conda activate my-jupyterbook-env
          jupyter-book build .
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4